services:
  - type: web
    name: playkart-campos
    env: static
    rootDir: ./playkart-campos-aa7565e305db0759e3e6c7135fea14a2dbbf6d3b
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
